node {

    withMaven(maven:'maven') {

        stage('Checkout') {
            git url: 'https://github.com/ayseayparcasiImst/microservices-junit.git', credentialsId: '3fd4127d-e3f3-423f-9490-e14fac1066d7', branch: 'main'
        }

        stage('Buildxxxxxxxxxxxxxxxxxx') {
            sh 'mvn clean install'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }
    }

     stage('Test') {
            steps {
                sh 'chmod +r pom.xml'
                sh 'chmod +r .mvn'
                sh 'chmod +r mvnw'
                sh 'chmod +r mvnw.cmd'
                sh 'chmod +x mvnw'
                sh 'chmod +x ./mvnw'
                sh './mvnw test'
                // bat '.\\mvnw test'
            }
            post {
                always {
                    junit '**/target/surefire-reports/TEST-*.xml'
                }
            }

}
